#!/bin/bash

scripts/build_html.py

## Export from 'public' directory
cp -r public/* out/

## Minify HTML
html-minifier-vars=--collapse-whitespace --minify-css true --minify-js true --process-scripts "application/javascript" --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-tag-whitespace
for html in out/*.html; do
    html-minifier $html-minifier-vars -o out\$html out\$html
done

## Export CSS
for css in styles/*.css; do
    csso styles/$css -o out/styles/$css
done
